config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # devise_for :users, controllers: {
  #   registrations: 'users/registrations',
  #   passwords: 'users/passwords'
  # }
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: "users#index"

  resources :users, only: [:show, :index]
  
  resources :posts do
    resources :other_posts
    collection do
      post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]
  
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :clean_conversations
  
  mount_uploader :image, ImageUploader

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'guest'
    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'admin_guest'
      user.admin = true
    end
  end

  def clean_conversations
    Conversation.where("(sender_id = ?) OR (recipient_id = ?)", self.id, self.id).destroy_all
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(@user.id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new_guest
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to posts_path, notice: 'ログインしました(ゲスト)'
  end

  def new_admin_guest
    guest_user = User.admin_guest
    sign_in guest_user   # ユーザーをログインさせる
    redirect_to posts_path, notice: 'ログインしました。(管理者ゲスト)'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end

  def show
    @favorite = current_user.favorite_posts
    @users = current_user.posts
  end

  private
  def user_params
    params.require(:user).permit(:image, :image_cache, :name, :comment)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section class="full">
  <p class="p1">
    ようこそ！ねこの和へ<br><br>
    保護猫と里親を結ぶアプリケーション
  </p>
  <p class="p2">
    保護した猫の里親をすぐに探してあげたい！<br><br>
    でも、サイトへの登録は難しくてなかなかできない・・・<br><br>
    そんな悩みをお持ちの方でも大丈夫！！<br><br>
    投稿までのアクションが簡単、スムーズ♪<br><br>
    投稿者とダイレクトメッセージもできて面倒な操作も無し！<br><br>
    ぜひ、お試しください。<br>
  </p>
</section>

app/views/users/show.html.erb
<div class="user_container">
  <p><%= image_tag @user.image.url if @user.image.present? %></p>
  
  <div class="user_field">
    <span class="user_text"><%= @user.name %>のページ</span>
    <% if current_user.id == @user.id %>
      <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark" %>
      <%= link_to 'メッセージ一覧', conversations_path, class: "btn btn-outline-dark" %>
    <% end %>
    <p class="box17"><%= @user.comment %></p>
  </div>
</div><br>

<h3 class="heading03">気になる一覧</h3>
<div class="user_area">
  <% @favorite.each do |post| %>
    <div class="user_post">
      <%= image_tag post.image.to_s, :size =>'150x150' %>
      <p class="user_comment"><%= link_to post.comment, post_path(post.id) %></p>
    </div>     
  <% end %><br><br>
</div><br>

<h3 class="heading03">投稿一覧</h3>
<div class="user_area">
  <% @users.each do |post| %>
    <div class="user_post">
      <%= image_tag post.image.to_s, :size =>'150x150' %>
      <p class="user_comment"><%= link_to post.comment, post_path(post.id) %></p>
    </div>     
  <% end %><br>
</div><br>

<div class="index_btn">
  <%= link_to "投稿する", new_post_path, class: "btn btn-outline-dark" %>
  <%= link_to "投稿一覧", posts_path, class: "btn btn-outline-dark" %>
</div>