config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # devise_for :users, controllers: {
  #   registrations: 'users/registrations',
  #   passwords: 'users/passwords'
  # }
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: "users#index"

  resources :users, only: [:show, :index]
  
  resources :posts do
    resources :other_posts
    collection do
      post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]
  
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_one :other_post, dependent: :destroy
  accepts_nested_attributes_for :other_post, update_only: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy

  validates :image, presence: true
  validates :comment, presence: true

  scope :search_prefecture, -> (search_prefecture) { where(prefecture: search_prefecture)}

  enum prefecture:{
     "エリアを選択":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
  }, _prefix: true

  enum gender:{ "性別を選択":0,♂　オス:1,♀　メス:2,不明:3 }, _prefix: true

  enum age:{
    "推定年齢を選択":0,
    １週間:1,２週間:2,３週間:3,１ヶ月:4,２ヶ月:5,３ヶ月:6,４ヶ月:7,
    ５ヶ月:8,６ヶ月:9,７ヶ月:10,８ヶ月:11,９ヶ月:12,１０ヶ月:13,１１ヶ月:14,
    １歳:15,２歳:16,３歳:17,４歳:18,５歳:19,６歳:20,
    ７歳:21,８歳:22,９歳:23,１０歳以上:24,
    不明:25
  }, _prefix: true

  geocoded_by :address
  after_validation :geocode
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :destroy, :update]

  def index
    if params[:search_prefecture].present?
      @posts = Post.search_prefecture(params[:search_prefecture])
    else
      @posts = Post.all
    end
    @posts = @posts.page(params[:page]).per(10)
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "新規投稿を作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @other_post = OtherPost.find_by(post_id: @post.id)
  end

  def edit
  end

  def update
    redirect_to posts_path if @post.user != current_user
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice:"投稿を削除しました！"
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end
  private
  def post_params
    params.require(:post).permit(:image, :image_cache, :comment, :breed, :gender, :age, :prefecture, :address, :latitude, :longitude)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def baria_user
    unless Post.find(params[:id]).user.id.to_i == current_user.id
        redirect_to posts_path(current_user)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/views/posts/_form.html.erb
<div class="post_area">
  <%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= @post.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="post_container">
      <div class="post_image">
        <%= image_tag(@post.image.url) if @post.image && @post.image.url %><br><br>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
      </div>
      <div class="post_comment">
        <%= form.text_area :comment, placeholder: "猫の簡単な紹介を入力", size: "50x8" %>
      </div>
    </div><br>

    <div  class="post_field">
      <div class="post_breed">
        <p><%= form.text_field :breed, placeholder: "種類を入力", size: 30 %></p>
      </div>

      <div class="post_gender">
        <p><%= form.select :gender, Post.genders.keys %></p>
      </div>

      <div class="post_age">
        <p><%= form.select :age, Post.ages.keys %></p>
      </div>

      <div>
        <p><%= form.select :prefecture, Post.prefectures.keys %></p>
      </div>

      <div>
        <%= form.text_field :address, placeholder: "保護した場所 ○○県○○市○○123", size: 30 %>
      </div><br>

      <%= form.submit name="投稿する"%>
    </div>
  <% end %><br>
  
  <%= link_to '投稿一覧画面に戻る', posts_path, class: "btn btn-outline-dark" %>
</div>

app/views/posts/confirm.html.erb
<div class="post_area">
  <h2>以下の内容で、送信する。</h2>
  <%= form_with(model: @post, url: posts_path, local: true) do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :comment %>
    <%= form.hidden_field :breed %>
    <%= form.hidden_field :gender %>
    <%= form.hidden_field :age %>
    <%= form.hidden_field :prefecture %>
    <%= form.hidden_field :address %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %><br><br>
    <table class="post_text_area">
      <th>紹介文</th>
      <td><%= @post.comment %></td>
    </table><br>

    <table class="post_text">
      <tr>
        <th>　　種類　　</th>
        <td><%= @post.breed %></td>
        <th>　　性別　　</th>
        <td><%= @post.gender %></td>
      </tr>
      <tr>
        <th>　推定年齢　</th>
        <td><%= @post.breed %></td>
        <th>　 エリア 　</th>
        <td><%= @post.prefecture %></td>
      </tr>
    </table><br><br>
    <p>保護した場所：<%= @post.address %></p>
    <%= form.submit "投稿する" %>
  <% end %><br>

  <%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div  class="post_area">
  <h2>投稿を編集する</h2>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<div class="search_area">
  <%= form_with(url: posts_path, method: :get, local: true) do |f| %>
    <%= f.select :search_prefecture, Post.prefectures.keys %>
    
    <%= f.submit '検索', id: 'search_button' %>
  <% end %><br>
</div>

<div class="index_area">
  <% @posts.each do |post| %>
    <div class="index_post">
      <%= image_tag post.image.to_s, :size =>'200x200' %>
      <p class="index_comment"><%= link_to post.comment, post_path(post.id) %></p>
    </div>
  <% end %><br>

</div><br><br>
<div class="index_btn">
  <div><%= paginate @posts %></div>
  <%= link_to "新規投稿", new_post_path, class: "btn btn-outline-dark" %>
  <%= link_to "プロフィール", user_path(current_user.id), class: "btn btn-outline-dark" %>
</div>

app/views/posts/new.html.erb
<div  class="post_area">
  <h2>新規投稿を作成する</h2>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="post_area"><h2>猫のステータス</h2></div>

<div class="post_container">
  <p><%= image_tag @post.image.url , size: "250x250" %></p>

  <div class="post_show_field">
    <span>
      <p>掲載日：<%= @post.created_at.strftime('%Y / %m / %d') %></p>
      <% unless @post.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to '気になる一覧から削除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to '気になる一覧に登録', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    </span>

    <% if @post.user == current_user %>
      <%= link_to "投稿を編集する", edit_post_path(@post.id), class: "btn btn-outline-dark" %>
      <%= link_to '投稿を削除する', post_path(@post.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "btn btn-outline-dark" %>
    <% end %>
  </div>
</div><br>

<div class="post_area">
  <p>
    投稿者: <%= link_to "#{@post.user.name}", user_path(@post.user) %>
    <% unless @post.user_id == current_user.id %>
    <%= link_to 'この投稿者にメッセージ', conversations_path(sender_id: current_user.id, recipient_id: @post.user.id), method: :post, class: "btn btn-outline-dark" %>
    <% end %>
  </p>
  <h3 class="heading03">基本情報</h3>
  <table class="post_text_area">
    <th>紹介文</th>
    <td><%= @post.comment %></td>
  </table><br>

  <table class="post_text">
    <tr>
      <th>　　種類　　</th>
      <td><%= @post.breed %></td>
      <th>　　性別　　</th>
      <td><%= @post.gender %></td>
    </tr>
    <tr>
      <th>　推定年齢　</th>
      <td><%= @post.breed %></td>
      <th>　 エリア 　</th>
      <td><%= @post.prefecture %></td>
    </tr>
  </table><br><br>

  <h3 class="heading03">詳細情報</h3>
  <% if @post.user == current_user %>
    <% if @other_post.blank? %>
      <%= link_to '詳細情報を追加する', new_post_other_post_path(@post), class: "btn btn-outline-dark" %><br><br>
    <% else %>
      <%= link_to '詳細情報を編集する', edit_post_other_post_path(@post, @other_post), class: "btn btn-outline-dark" %><br><br>
    <% end %>
  <% end %>

  <% if @other_post.present? %>
    <table class="post_text">
      <tr>
        <th>ワクチン接種</th>
        <td><%= @other_post.vaccination %></td>
        <th> 去勢／避妊 </th>
        <td><%= @other_post.operation %></td>
      </tr>
      <tr>
        <th> 単身者応募 </th>
        <td><%= @other_post.single %></td>
        <th> 高齢者応募 </th>
        <td><%= @other_post.old_age %></td>
      </tr>
    </table><br>

    <table class="post_text_area">
      <th>健康状態</th>
      <td><%= @other_post.health_status %></td>
    </table><br>

    <table class="post_text_area">
      <th>性格／特徴</th>
      <td><%= @other_post.character %></td>
    </table><br>

    <table class="post_text_area">
      <th>引き渡し条件</th>
      <td><%= @other_post.surrender %></td>
    </table><br>

    <table class="post_text_area">
      <th>備考</th>
      <td><%= @other_post.note %></td>
    </table><br>

    <% else %> 
  <% end %>
  <br>
  <hr>
  <% if @post.address.present? %>
    <h5>保護した場所：<%= @post.address %></h5>

    <div id="map" style='width: 100%; height: 300px;'></div>
  
    <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers([
          {
            "lat": <%= @post.latitude %>,
            "lng": <%= @post.longitude %>,
        "infowindow": '<p><%= @post.address %></p><p><%= link_to "Googleマップで見る" ,"https://maps.google.co.jp/maps?q=loc:#{@post.latitude},#{@post.longitude}&iwloc=J",target: "_blank" %></p>'
          }
        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(17);
      });
    </script><br>
  <% end %>

  <%= link_to '投稿一覧画面に戻る', posts_path, class: "btn btn-outline-dark" %>
</div>