config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # devise_for :users, controllers: {
  #   registrations: 'users/registrations',
  #   passwords: 'users/passwords'
  # }
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: "users#index"

  resources :users, only: [:show, :index]
  
  resources :posts do
    resources :other_posts
    collection do
      post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]
  
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nekonowa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=<%= ENV['GMAP_API_KEY'] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>

  <body class="wrapper <%= controller.controller_name %>_<%= controller.action_name %>">
    <header>
      <div class="background"><p>〜  ねこの和 〜</p></div>
    </header>

    <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:rgb(238, 238, 238);">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <span class="navbar-brand"><%= link_to "管理画面", rails_admin_path %></span>
              <% end %>
              <span class="nav_btn"><%= link_to "トップページ", users_path %></span>
              <span class="nav_btn"><%= link_to "プロフィール", user_path(current_user.id) %></span>
              <span class="nav_btn"><%= link_to "新規投稿", new_post_path %></span>
              <span class="nav_btn"><%= link_to "投稿一覧", posts_path %></span>
              <span class="nav_btn"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></span>
            <% else %>
              <span class="nav_btn"><%= link_to "トップページ", users_path %></span>
              <span class="nav_btn"><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></span>
              <span class="nav_btn"><%= link_to 'ゲストログイン（管理者）', users_admin_guest_sign_in_path, method: :post %></span>
              <span class="nav_btn"><%= link_to "新規アカウント登録", new_user_registration_path %></span>
              <span class="nav_btn"><%= link_to "ログイン", new_user_session_path %></span>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>   

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
       <hr>
    <% end %>
   
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <div class="main_content">
    <%= yield %>
    </div>

    <footer class="footer">
      <p class="copy">&copy;nekonowa</p>
    </footer>
  </body>
</html>